name: Build UIBase
on:
  push:
    branches: master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout mob
        uses: actions/checkout@master
        with:
          repository: modorganizer2/mob
          path: ./mob
      - name: Cache mob
        id: cache-mob
        uses: actions/cache@v3
        with:
          path: |
            ./mob/mob.exe
          key: ${{ runner.OS }}-mob-cache-${{ hashFiles('mob/.git/refs/heads/master') }}
          restore-keys: |
            ${{ runner.OS }}-mob-cache-
      - if: ${{ steps.cache-mob.outputs.cache-hit != 'true' }}
        name: Build mob
        run: .\mob\bootstrap.ps1
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.1
          modules: qtpositioning qtwebchannel qtwebengine qtwebsockets
          cache: true
      - name: Add Qt bins to PATH
        run: echo "${QT_ROOT_DIR }/msvc2019_64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./build
            !./build/modorganizer_super
          key: ${{ runner.OS }}-mo2-dependencies-${{ hashFiles('mob/.git/refs/heads/master') }}
          restore-keys: |
            ${{ runner.OS }}-mo2-dependencies-
      - if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' }}
        name: Build dependencies with mob
        run: .\mob\mob.exe -l 4 -d . build fmt gtest spdlog boost
      - name: Build dependencies log
        uses: actions/upload-artifact@v3
        with:
          name: build-dependencies-log
          path: |
            mob.log
      - name: Build cmake_common
        run: .\mob\mob.exe -l 4 -d . build
          --ignore-uncommitted-changes
          --redownload --reextract --reconfigure --rebuild
          cmake_common
      - uses: actions/checkout@v3
        with:
          path: ./build/modorganizer_super/uibase
      - name: Build UIBase
        run: .\mob\mob.exe -l 5 -d . build --no-fetch-task --no-pull uibase
