name: Lint Plugin Python
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: "15"
          check-path: "."
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: isort/isort-action@master
      - uses: psf/black@stable
